Hooking/Models/CottageAppeal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Hooking.Models
{
    public class CottageAppeal : BaseModel
    {
        public string CottageId { get; set; }
        [DisplayName("Datum objave")]
        public DateTime CreationTime { get; } = DateTime.Now;
        [DisplayName("Žalba")]
        public string AppealContent { get; set; } // limited to 300 chars
        [DisplayName("Email korisnika")]
        public string UserEmail { get; set; }
    }
}

Hooking/Controllers/CottageAppealsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hooking.Data;
using Hooking.Models;
using Microsoft.AspNetCore.Identity;
using Nito.AsyncEx.Synchronous;
using Microsoft.AspNetCore.Identity.UI.Services;
using Newtonsoft.Json;
using System.IO;

namespace Hooking.Controllers
{
    public class CottageAppealsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;

        public CottageAppealsController(ApplicationDbContext context,
            UserManager<IdentityUser> userManager, 
            IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;

            using StreamReader reader = new StreamReader("./Data/emailCredentials.json");
            string json = reader.ReadToEnd();
            _emailSender = JsonConvert.DeserializeObject<EmailSender>(json);
        }

        // GET: CottageAppeals
        public async Task<IActionResult> Index()
        {


            return View(await _context.CottageAppeal.ToListAsync());
        }

        public IActionResult AnswerAppeal(Guid id)
        {
            CottageAppeal appeal = _context.CottageAppeal.Find(id);
            return View(appeal);
        }

        private string GetCottageOwnerEmailFromAppeal(CottageAppeal appeal)
        {
            Cottage cottage = _context.Cottage.Find(Guid.Parse(appeal.CottageId));
            CottageOwner owner = _context.CottageOwner.Find(Guid.Parse(cottage.CottageOwnerId));
            UserDetails userDetails = _context.UserDetails.Find(Guid.Parse(owner.UserDetailsId));
            return _userManager.FindByIdAsync(userDetails.IdentityUserId).WaitAndUnwrapException().Email;
        }

        public async Task<IActionResult> SubmitAnswer([Bind("CottageId,AppealContent,UserEmail,Id,RowVersion")] CottageAppeal appeal, string answer)
        {
            await _emailSender.SendEmailAsync(appeal.UserEmail, "Odgovor na žalbu", answer);
            string ownerEmail = GetCottageOwnerEmailFromAppeal(appeal);
            await _emailSender.SendEmailAsync(ownerEmail, "Odgovor na žalbu", answer);
            appeal = _context.CottageAppeal.FirstOrDefault(a => a.Id == appeal.Id);
            if (appeal == null)
            {
                Debug.WriteLine("Concurrency error!");
                return RedirectToAction("ConcurrencyError", "Home");
            }
            _context.CottageAppeal.Remove(appeal);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                Debug.WriteLine("Concurrency error!");
                return RedirectToAction("ConcurrencyError", "Home");
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: CottageAppeals/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cottageAppeal = await _context.CottageAppeal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cottageAppeal == null)
            {
                return NotFound();
            }

            return View(cottageAppeal);
        }

        private async Task<bool> cottageAppealExists(CottageAppeal cottageAppeal,string cottageId)
        {
            var user = await _userManager.GetUserAsync(User);


            foreach (CottageAppeal ctgAppeal in _context.CottageAppeal.ToList())
            {
                var appealUser = _context.Users.Where(m => m.Email == ctgAppeal.UserEmail);
                if (user.Email == ctgAppeal.UserEmail && ctgAppeal.CottageId == cottageId)
                    return true;
            }

            return false;
        }

        // GET: CottageAppeals/Create
        public IActionResult Create(Guid id, String cottageOwnerId)
        {
            Cottage ctg = _context.Cottage.Where(m => m.Id == id).FirstOrDefault();
            CottageOwner ctgOwner = _context.CottageOwner.Where(m => m.Id == Guid.Parse(cottageOwnerId)).FirstOrDefault();
            UserDetails cottageOwnerUser = _context.UserDetails.Where(m => m.Id == Guid.Parse(ctgOwner.UserDetailsId)).FirstOrDefault();

            ViewData["Cottage"] = ctg;
            ViewData["CottageOwner"] = cottageOwnerUser;
            return View();
        }

        // POST: CottageAppeals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/CottageAppeals/Create/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid id,[Bind("CottageId,AppealContent,Id,RowVersion")] CottageAppeal cottageAppeal)
        {

            Debug.WriteLine("cottageId je " + id.ToString());
       //     Debug.WriteLine("prosledjeni email je" + cottageAppeal.UserEmail.ToString());
            if (ModelState.IsValid)
            {
                cottageAppeal.Id = Guid.NewGuid();
                cottageAppeal.CottageId = id.ToString();
                if (cottageAppeal.UserEmail==null)
                {
                    var user = await _userManager.GetUserAsync(User);
                    cottageAppeal.UserEmail = user.Email;
                }
                if(!(await cottageAppealExists(cottageAppeal, cottageAppeal.CottageId)))
                {
                    _context.Add(cottageAppeal);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction("Index", "Cottages");
            }
            return View(cottageAppeal);
        }

        // GET: CottageAppeals/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cottageAppeal = await _context.CottageAppeal.FindAsync(id);
            if (cottageAppeal == null)
            {
                return NotFound();
            }
            return View(cottageAppeal);
        }

        // POST: CottageAppeals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CottageId,AppealContent,Id,RowVersion")] CottageAppeal cottageAppeal)
        {
            if (id != cottageAppeal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cottageAppeal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CottageAppealExists(cottageAppeal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cottageAppeal);
        }

        // GET: CottageAppeals/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cottageAppeal = await _context.CottageAppeal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cottageAppeal == null)
            {
                return NotFound();
            }

            return View(cottageAppeal);
        }

        // POST: CottageAppeals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var cottageAppeal = await _context.CottageAppeal.FindAsync(id);
            _context.CottageAppeal.Remove(cottageAppeal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CottageAppealExists(Guid id)
        {
            return _context.CottageAppeal.Any(e => e.Id == id);
        }
    }
}

Hooking/Views/CottageAppeals/AnswerAppeal.cshtml
@model Hooking.Models.CottageAppeal

@{
    ViewData["Title"] = "Odgovor";
}

<div class="row">
    <div class="col-md-4">
        <form asp-controller="CottageAppeals" asp-action="SubmitAnswer">
            <div class="form-group">
                <label class="control-label">Odgovor</label>
                <textarea class="form-control" name="answer" rows="3" cols="20"></textarea>
            </div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UserEmail" />
            <input type="hidden" asp-for="CottageId" />
            <div class="form-group">
                <input type="submit" value="Odgovori" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="CottageAppeals" asp-action="Index">Nazad</a>
</div>

Hooking/Views/CottageAppeals/Create.cshtml
@model Hooking.Models.CottageAppeal

@{
    ViewData["Title"] = "Create";
}

@{
    Cottage ctg = (Cottage)ViewData["Cottage"];
    UserDetails ctgOwner = (UserDetails)ViewData["CottageOwner"];

}

<h4>Zalba na vikendicu i vlasnika vikendice</h4>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Naziv vikendice
        </dt>
        <dd class="col-sm-10">
            @ctg.Name
        </dd>
        <dt class="col-sm-2">
            Ime vlasnika 
        </dt>
        <dd class="col-sm-10">
            @ctgOwner.FirstName
        </dd>
        <dt class="col-sm-2">
            Prezime vlasnika 
        </dt>
        <dd class="col-sm-10">
            @ctgOwner.LastName
        </dd>
    </dl>
</div>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="AppealContent" class="control-label"></label>
                        <input asp-for="AppealContent" class="form-control" />
                        <span asp-validation-for="AppealContent" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Potvrdi" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a href='javascript:history.go(-1)'>Nazad</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

Hooking/Views/CottageAppeals/Delete.cshtml
@model Hooking.Models.CottageAppeal

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CottageAppeal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CottageId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CottageId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppealContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppealContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RowVersion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RowVersion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Hooking/Views/CottageAppeals/Details.cshtml
@model Hooking.Models.CottageAppeal

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CottageAppeal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CottageId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CottageId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppealContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppealContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RowVersion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RowVersion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Hooking/Views/CottageAppeals/Edit.cshtml
@model Hooking.Models.CottageAppeal

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CottageAppeal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CottageId" class="control-label"></label>
                <input asp-for="CottageId" class="form-control" />
                <span asp-validation-for="CottageId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppealContent" class="control-label"></label>
                <input asp-for="AppealContent" class="form-control" />
                <span asp-validation-for="AppealContent" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hooking/Views/CottageAppeals/Index.cshtml
@model IEnumerable<Hooking.Models.CottageAppeal>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
          
            <th>
                @Html.DisplayNameFor(model => model.AppealContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserEmail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
          
            <td>
                @Html.DisplayFor(modelItem => item.AppealContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserEmail)
            </td>
            <td>
                <a asp-controller="CottageAppeals" asp-action="AnswerAppeal" asp-route-id="@item.Id">Odgovori</a>
            </td>
        </tr>
}
    </tbody>
</table>